[project]
name = "conference-helper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "pytest>=8.4.2",
    "structlog>=25.5.0",
    "tabulate>=0.9.0",
]
